config/routes.rb
Computek::Application.routes.draw do

  devise_for :users,
             :path_names => { :sign_in => 'login', :sign_out => 'logout',
                              :password => 'secret', :confirmation => 'verification' },
             :controllers => { :registrations => "registrations" }

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
    end
  end

  resources :incidents, :except => [:destroy]
  resources :mobile_users, :only => [:create]

  root :to => 'incidents#index'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
  CATEGORY = {"Abduction" => "ABD", "Domestic Violence" => "DOV",
              "Armed Robbery" => "ARB", "Hijack" => "HIJ",
              "Arson" => "ARS", "Shooting" => "SHO",
              "Assault" => "ASL", "Murder" => "MUR",
              "Attempted Murder" => "ATM", "Rape" => "RAP",
              "Bombing" => "BOM", "Fighting" => "FIG",
              "Terror Attack" => "TAT", "Terror Suspect" => "TSU"
  }
  STATUS = ["Open", "In Progress", "Suspended", "Withdrawn", "Closed"]

  attr_accessible :category, :mobile_user, :mobile_user_id, :status,
                  :reference, :location_attributes, :location, :user, :user_id

  attr_accessible :avatar
  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/assets/missing.png"
  validates_attachment :avatar,
                       :content_type => { :content_type => /(image\/jpeg)|(application\/octet-stream)/ },
                       :size => { :in => 0..10.megabytes }

  belongs_to :mobile_user
  belongs_to :user
  has_one :location
  accepts_nested_attributes_for :location

  validates_presence_of :location, :mobile_user, :category
  before_create :generate_reference_number
  before_save :default_values

  def as_json(options={})
    {:id => self.id,
     :category => CATEGORY.select{|name, _| name == self.category}.first.first,
     :location => self.location.street,
     :updated_at => self.updated_at.to_s(:short),
     :created_at => self.created_at.to_s(:short),
     :reference => self.reference,
     :status => self.status,
     :mobile_user_contact => self.mobile_user.mobile_contact,
     :mobile_user_name => self.mobile_user.name }
  end

  private
  def default_values
    save_default_user
    self.status ||= STATUS[0]
  end

  def generate_reference_number
    self.reference = "%s%d" % [CATEGORY[self.category], Time.now.to_i]
  end

  def save_default_user
    self.user ||= User.find_by_role("control_officer") if self.user.nil?
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :create

  def index
    if current_user.role.to_sym  == :control_officer
      @incidents = Incident.where(:user_id => current_user.id).page(params[:page]).order('updated_at DESC')
    else
      @incidents = Incident.page(params[:page]).order('updated_at DESC')
    end

    @incidents = @incidents.where("updated_at > ?", params[:last_update_time]) if params[:last_update_time]

    respond_to do |format|
      format.html
      format.any(:xml, :json) { render request.format.to_sym => @incidents }
    end
  end

  def create
    incident = Incident.new(params[:incident])
    if incident.save
      render :json => {:reference => incident.reference, :id => incident.id}.to_json, :status => :created
    else
      render :json => incident.errors, :status => :unprocessable_entity
    end
  end

  def edit
    @incident = Incident.find(params[:id])
  end

  def update
    @incident = Incident.find(params[:id])
    if @incident.update_attributes(params[:incident])
      respond_to do |format|
        format.html do
          redirect_to({:action => "edit"}, :notice => 'Incident was successfully updated.')
        end
        format.any(:xml, :json) {render request.format.to_sym => @incident, :status => :created }
      end
    else
      render :action => "edit"
    end
  end
end

app/helpers/incident_helper.rb
module IncidentHelper
end

app/views/incidents/edit.html.erb
<h2>Edit Incident</h2>
<%= form_for(@incident, :html => {:class => "form-horizontal"}) do |f| %>
    <% if @incident.errors.any? %>
        <div id="alert alert-block alert-error fade in">
          <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>
          <ul>
            <% @incident.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="control-group">
      <%= f.label :reference, :class => "control-label" %>
      <div class="controls">
        <%= f.label :reference, @incident.reference, :class => "control-label" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :category, :class => "control-label" %>
      <div class="controls">
        <%= f.collection_select :category, Incident::CATEGORY, :first, :first%>
      </div>
    </div>

    <% if can? :update_incident_user, current_user %>
        <div class="control-group">
          <%= f.label :user_id, :class => "control-label" %>
          <div class="controls">
            <%= f.collection_select :user_id, User.find_all_by_role(:control_officer), :id, :name%>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :status, :class => "control-label" %>
      <div class="controls">
        <%= f.collection_select :status, Incident::STATUS, :to_s, :to_s%>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Update", :class => "btn" %>
    </div>

<% end %>

app/views/incidents/index.html.erb
<h2>INCIDENT REPORT</h2>
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th>Requestor</th>
      <th>Location</th>
      <th>Mobile Number</th>
      <th>Picture</th>
      <th>Status</th>
      <th>Handling Officer</th>
      <th>DateTime</th>
      <th>Reference</th>
    </tr>
  </thead>
  <tbody>
    <% @incidents.each do |incident| %>
    <tr>
      <td><%= incident.category %></td>
      <td><%= incident.mobile_user.name %></td>
      <td><%= incident.location.street %></td>
      <td><%= incident.mobile_user.mobile_contact %></td>
      <td><%= image_tag incident.avatar.url(:medium) %></td>
      <td><%= incident.status %></td>
      <td><%= incident.user.name %></td>
      <td><%= incident.updated_at %></td>
      <td><%= link_to incident.reference, edit_incident_path(incident) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @incidents, :class => "pagination pagination-centered", :previous_label => "<<", :next_label => ">>" %>